### ISSUE TITLE
Using GatsbyJS

### ISSUE THREAD

**Issue by cr101** [fus-marcom/franciscan-react#33]
My understanding is that GatsbyJS is great for building blogs, portfolio, documentation or small personal websites where _**the content rarely changes**_. Have a look at their [showcase list of websites built with Gatsby](https://github.com/gatsbyjs/gatsby) and see for yourself.

I have not seen any evidence that GatsbyJS is a great tool to build interactive and dynamic large web apps.

I believe that the project built with NextJS will be just as fast if `lru-cache` and a WordPress database caching plugin like [W3 Total Cache](https://wordpress.org/plugins/w3-total-cache/) are used. 
You might also want to use [Cloudflare](https://www.cloudflare.com/) which will cache all the images, CSS and JS files and it's free.

And you will not have to rebuild the site every time the content changes at all or when a new event or news item is added/updated.

It sounds to me like complicating things unnecessarily. That's just my 2c worth.

PS: Early next year WordPress will be releasing a new editor called "[Gutenberg](https://github.com/WordPress/gutenberg)" which is built using ReactJS.

**Comment by pantharshit00** [comment]
I totally agree with @cr101 if need static exports die hardly next can also do that using `next export` see https://github.com/zeit/next.js/#static-html-export . It will be a waste of time to implement gatsby but it is up to you.

**Comment by JesseRWeigel** [comment]
You both make good points. 

I do plan on using lru-cache, caching on WP, and cloudflare (or something similar).

When it comes to rebuilding, I was told that rebuilds can be triggered automatically when content updates. The site will not have any downtime during a rebuild because the old version will still be served until the new one is ready.

Based on discussions I had at Nodevember, it seemed like using Gatsby and Netlify would end up being a simpler, and possible less expensive setup. 

I am more comfortable with Next.js and I know it will work for our use case, but I would like to at least test Gatsby. I think there is educational value in building it out at least enough to test it against Next.js. I am assuming that the work to get it to that point will not be significant. We just need one page to pull in data for testing.

Thanks again to sharing your opinions and knowledge. I really do appreciate your honest feedback, even and especially when it isn't in total agreement with mine. Please let me know if I am mistaken in any way.

**Comment by pantharshit00** [comment]
yeah benchmarking would be fun we should be using apache bench ab for benchmarking. But make sure you use next js statically exported as a option with service worker configured as not to make next weaker.

**Comment by cr101** [comment]
@JesseRWeigel Will you have a search page on the new website? If so, will you allow users to filter the search results? And if that's the case, how will all that work with GatsbyJS? Searching and filtering thousands of GatsbyJS nodes in the client will potentially kill the user's browser!

**Comment by JesseRWeigel** [comment]
@cr101 That is a very good point. I was thinking about checking out some third party services for search.

**Comment by pantharshit00** [comment]
Maybe https://algolia.com

**Comment by cr101** [comment]
Algolia is great but it's very expensive!
