### ISSUE TITLE
Rebuild website with updated content

### ISSUE THREAD

**Issue by cr101** [fus-marcom/franciscan-react#8]
I've got some questions after watching the [P5D2 video on YouTube](https://www.youtube.com/watch?v=nufLF1kcn_4&t=14s).
In production, this is a static site and content is only updated when you do a fresh build and deploy to your host. There is no way for Gatsby to know that you made changes to your database.
Does the content on the Franciscan University website change at all? If so, there will be a manual process involved in refreshing the content on the live site.
I'm not sure how many web pages the Franciscan website has but I wonder how long `gatsby build` will take.

**Comment by pantharshit00** [comment]
We will be pulling dynamic data from wordpress. see https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-wordpress 


Other parts like about dont change that much so they will be static.

**Comment by pantharshit00** [comment]
@JesseRWeigel close this issue

**Comment by cr101** [comment]
@pantharshit00 Yes, I'm aware of the gatsby-source-wordpress package that pulls data from WordPress, however, if the content changes in the database after you run 'gatsby build' then you will need to manually run 'gatsby build' again to fetch the newly added/updated content and rebuild the site.

**Comment by pantharshit00** [comment]
in #13 I have ported this project to next js. We might still use gatsby we dont know. May be can setup a webhook to trigger a rebuild

**Comment by JesseRWeigel** [comment]
@cr101 thanks for bringing this up!

At this point I will keep what has been done with Gatsby so far on a separate branch. Because we will be load balancing over multiple servers. We could run rebuilds one at a time and have no downtime. I am concerned about the rebuild time, because the current site has 3000+ pages. We plan on making the new site smaller, but it will still be large.

I have set up a branch from @pantharshit00 's PR converting everything over to Next. This should work for our purposes. 

I am wondering if it would be best to just use create-react-app and set up our own SSR. Any thoughts on this? If this isn't a good idea, I will just merge the Next branch into master and carry on.

In any case, I appreciate the debate @cr101  and @pantharshit00 !

**Comment by KyleAMathews** [comment]
Builds aren't a problem generally — they're easy to automate with webhooks and a service like https://www.netlify.com/

And avoiding run-time SSR means you don't have to worry about "load balancing" or servers at all as the site is simply served from the CDN — so no operations + much faster sites.

**Comment by pantharshit00** [comment]
@KyleAMathews Yeah gatsby do this the best. See we are converting http://franciscan.edu
Will gatsby will suit this project

**Comment by KyleAMathews** [comment]
Absolutely! Stuff like search is probably best to do with an external service like https://www.algolia.com/ — I know of several Gatsby sites that use Algolia for search e.g. https://reactjs.org/

**Comment by cr101** [comment]
@KyleAMathews Algolia is great but it's very [expensive](https://www.algolia.com/pricing).
